/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pocLibreria.gui;

/**
 *
 * @author nikol
 */
public class GuiPrincipalLibreria extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public GuiPrincipalLibreria() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuReportesLibreria = new javax.swing.JMenu();
        SubmenuActualizarLibreria = new javax.swing.JMenuItem();
        SubmenuSumatoriaLibreria = new javax.swing.JMenuItem();
        SubmenuContrarRegistrosLibreria = new javax.swing.JMenuItem();
        MenuConsultasLibreria = new javax.swing.JMenu();
        SubmenuBuscarLibroLibreria = new javax.swing.JMenuItem();
        SubMenuListarLibreria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Gestionar");

        jMenuItem2.setText("Agregar Libreria");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Eliminar Libreria");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        MenuReportesLibreria.setText("Reportes");

        SubmenuActualizarLibreria.setText("Actualizar Libreria ");
        SubmenuActualizarLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuActualizarLibreriaActionPerformed(evt);
            }
        });
        MenuReportesLibreria.add(SubmenuActualizarLibreria);

        SubmenuSumatoriaLibreria.setText("Sumatoria Libreria");
        SubmenuSumatoriaLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuSumatoriaLibreriaActionPerformed(evt);
            }
        });
        MenuReportesLibreria.add(SubmenuSumatoriaLibreria);

        SubmenuContrarRegistrosLibreria.setText("Contar Registros ");
        MenuReportesLibreria.add(SubmenuContrarRegistrosLibreria);

        jMenuBar1.add(MenuReportesLibreria);

        MenuConsultasLibreria.setText("Consultas");

        SubmenuBuscarLibroLibreria.setText("Buscar Libreria");
        MenuConsultasLibreria.add(SubmenuBuscarLibroLibreria);

        SubMenuListarLibreria.setText("Listar Libreria");
        SubMenuListarLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuListarLibreriaActionPerformed(evt);
            }
        });
        MenuConsultasLibreria.add(SubMenuListarLibreria);

        jMenuBar1.add(MenuConsultasLibreria);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void SubMenuListarLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuListarLibreriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubMenuListarLibreriaActionPerformed

    private void SubmenuActualizarLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuActualizarLibreriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmenuActualizarLibreriaActionPerformed

    private void SubmenuSumatoriaLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuSumatoriaLibreriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmenuSumatoriaLibreriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipalLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipalLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipalLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipalLibreria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPrincipalLibreria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConsultasLibreria;
    private javax.swing.JMenu MenuReportesLibreria;
    private javax.swing.JMenuItem SubMenuListarLibreria;
    private javax.swing.JMenuItem SubmenuActualizarLibreria;
    private javax.swing.JMenuItem SubmenuBuscarLibroLibreria;
    private javax.swing.JMenuItem SubmenuContrarRegistrosLibreria;
    private javax.swing.JMenuItem SubmenuSumatoriaLibreria;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
