/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poclibreria.gui;

<<<<<<< HEAD
import java.io.RandomAccessFile;
import javax.swing.JOptionPane;
import pocLibreria.Servicios.ServiciosLibro;
import poclibreria.Modelo.Libro;

=======
>>>>>>> 54bbe114d8fc81fc3d631e5643cfb360d0f13972
/**
 *
 * @author nikol
 */
public class VentanaEliminar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEliminar
     */
    public VentanaEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void TextCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCodigoActionPerformed

    private void TextEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEstadoActionPerformed

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed

    }//GEN-LAST:event_TextNombreActionPerformed

    private void ButEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButEliminarActionPerformed
        Integer codigo;
        String nombre, estado, strCodigo;
        Double precio;
        Boolean disponible;
        Libro libro;

        strCodigo = TextCodigo.getText().trim();
        codigo = Integer.parseInt(strCodigo);
        
        libro = ServiciosLibro.buscarLibro(codigo);
        
        if (libro != null){
             try {
            RandomAccessFile file = new RandomAccessFile("data//libro.txt", "rw");
            while (file.getFilePointer() < file.length()) {
                Long posInicioRegistro = file.getFilePointer();
                codigo = file.readInt();
                nombre = file.readUTF().trim();
                precio = file.readDouble();
                disponible = file.readBoolean();
                estado = file.readUTF();
                if (codigo == libro.getCodigo()){
                    long posBoolean = posInicioRegistro + 4 + (2 + nombre.getBytes().length) + 8;
                    file.seek(posBoolean);       
                    file.writeBoolean(false);
                    
                    JOptionPane.showMessageDialog(this, "Estado de disponibilidad actualizado correctamente.");
                    break;
                }
            }
            
        } 
            catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error"+ e);
        }
        }
        else{
            JOptionPane.showMessageDialog(this, "El libro no existe");
                    
        }
       


    }//GEN-LAST:event_ButEliminarActionPerformed

=======
>>>>>>> 54bbe114d8fc81fc3d631e5643cfb360d0f13972
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
