/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poclibreria.gui;

import java.io.RandomAccessFile;
import javax.swing.JOptionPane;
import pocLibreria.Servicios.ServiciosLibreria;
import poclibreria.Modelo.Libro;
import pucLiberiaUtils.StringUtils;

/**
 *
 * @author nikol
 */
public class VentanaActualizar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaActualizar
     */
    public VentanaActualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        TextPrecioViejo = new javax.swing.JTextField();
        TextEstadoViejo = new javax.swing.JTextField();
        TextCodigoViejo = new javax.swing.JTextField();
        TextNombreViejo = new javax.swing.JTextField();
        CheckNoViejo = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CheckSiViejo = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        ButBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ButActualizar = new javax.swing.JButton();
        TextPrecio1 = new javax.swing.JTextField();
        TextEstado1 = new javax.swing.JTextField();
        TextCodigo1 = new javax.swing.JTextField();
        TextNombre1 = new javax.swing.JTextField();
        CheckNo1 = new javax.swing.JCheckBox();
        CheckSi1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Estado:");

        TextPrecioViejo.setEditable(false);

        TextEstadoViejo.setEditable(false);
        TextEstadoViejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEstadoViejoActionPerformed(evt);
            }
        });

        TextCodigoViejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCodigoViejoActionPerformed(evt);
            }
        });

        TextNombreViejo.setEditable(false);
        TextNombreViejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreViejoActionPerformed(evt);
            }
        });

        CheckNoViejo.setText("NO");
        CheckNoViejo.setEnabled(false);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        CheckSiViejo.setText("SI");
        CheckSiViejo.setEnabled(false);
        CheckSiViejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckSiViejoActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio:");

        ButBuscar.setText("Buscar");
        ButBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Disponible:");

        ButActualizar.setText("Actualizar");
        ButActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButActualizarActionPerformed(evt);
            }
        });

        TextEstado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEstado1ActionPerformed(evt);
            }
        });

        TextCodigo1.setEditable(false);
        TextCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCodigo1ActionPerformed(evt);
            }
        });

        TextNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombre1ActionPerformed(evt);
            }
        });

        CheckNo1.setText("NO");

        CheckSi1.setText("SI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TextPrecioViejo)
                                            .addComponent(TextEstadoViejo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckSiViejo)
                                        .addGap(22, 22, 22)
                                        .addComponent(CheckNoViejo)
                                        .addGap(34, 34, 34))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextCodigoViejo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextNombreViejo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextPrecio1)
                                    .addComponent(TextEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(CheckSi1)
                                    .addGap(22, 22, 22)
                                    .addComponent(CheckNo1)
                                    .addGap(34, 34, 34)))
                            .addComponent(TextCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(ButBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButActualizar)
                        .addGap(97, 97, 97))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TextCodigoViejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextNombreViejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextPrecioViejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckNoViejo)
                            .addComponent(CheckSiViejo)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextEstadoViejo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextCodigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CheckNo1)
                            .addComponent(CheckSi1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButBuscar)
                    .addComponent(ButActualizar))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextEstadoViejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEstadoViejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEstadoViejoActionPerformed

    private void TextCodigoViejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCodigoViejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCodigoViejoActionPerformed

    private void TextNombreViejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreViejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreViejoActionPerformed

    private void ButBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButBuscarActionPerformed
        String nombre, estado, strCodigo, strPrecio;
        int codigo;
        boolean disponible;
        Libro libro;

        strCodigo = TextCodigoViejo.getText().trim();
        codigo = Integer.parseInt(strCodigo);

        libro = ServiciosLibreria.buscarLibro(codigo);

        if (libro != null) {
            TextCodigoViejo.setText(String.valueOf(libro.getCodigo()));
            TextNombreViejo.setText(libro.getNombre());
            TextPrecioViejo.setText(String.valueOf(libro.getPrecio()));
            TextEstadoViejo.setText(libro.getEstado());
            if (libro.isDisponible() == true) {
                CheckSiViejo.setSelected(true);
            } else {
                CheckNoViejo.setSelected(false);
            }
            TextCodigo1.setText(String.valueOf(libro.getCodigo()));
            TextNombre1.setText(libro.getNombre());
            TextPrecio1.setText(String.valueOf(libro.getPrecio()));
            TextEstado1.setText(libro.getEstado());
            if (libro.isDisponible() == true) {
                CheckSi1.setSelected(true);
            } else {
                CheckNo1.setSelected(false);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Libro no encontrado!");
        }
    }//GEN-LAST:event_ButBuscarActionPerformed

    private void ButActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButActualizarActionPerformed
        String pNombre, pEstado, StrCodigo;
        int pCodigo;
        double pPrecio;
        boolean pDisponible;
        Libro libro;
        try {
            pCodigo = Integer.parseInt(TextCodigo1.getText());
            pNombre = TextNombre1.getText();
            pEstado = TextEstado1.getText();
            pPrecio = Double.parseDouble(TextPrecio1.getText());
            if (CheckSi1.isSelected() && !CheckNo1.isSelected()) {
                pDisponible = true;
            } else if (!CheckSi1.isSelected() && CheckNo1.isSelected()) {
                pDisponible = false;
            } else if (CheckSi1.isSelected() && CheckNo1.isSelected()) {
                JOptionPane.showMessageDialog(this, "Solo se puede seleccionar un estado de disponibilidad");
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Se tiene que selecionar un estado de disponibilidad");
                return;
            }
            
            
            RandomAccessFile file = new RandomAccessFile("data//libro.txt", "rw");
            while (file.getFilePointer() < file.length()) {
                int codigo = file.readInt();
                if (codigo == pCodigo) {
                    file.seek(file.getFilePointer() - 4);
                    file.writeInt(pCodigo);
                    file.writeUTF(StringUtils.formatearCadena(pNombre, 25));
                    file.writeDouble(pPrecio);
                    file.writeBoolean(pDisponible);
                    file.writeUTF(StringUtils.formatearCadena(pEstado, 5));
                    JOptionPane.showMessageDialog(this, "Se Actulizo el libro correctamente");
                    break;
                    
                } else {
                    file.readUTF();
                    file.readDouble();
                    file.readBoolean();
                    file.readUTF();

                }

                
            }
            JOptionPane.showMessageDialog(this, "No se encontro el libro en lista");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e);
        }


    }//GEN-LAST:event_ButActualizarActionPerformed

    private void TextEstado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEstado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEstado1ActionPerformed

    private void TextCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCodigo1ActionPerformed

    private void TextNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombre1ActionPerformed

    private void CheckSiViejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckSiViejoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckSiViejoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaActualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaActualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButActualizar;
    private javax.swing.JButton ButBuscar;
    private javax.swing.JCheckBox CheckNo1;
    private javax.swing.JCheckBox CheckNoViejo;
    private javax.swing.JCheckBox CheckSi1;
    private javax.swing.JCheckBox CheckSiViejo;
    private javax.swing.JTextField TextCodigo1;
    private javax.swing.JTextField TextCodigoViejo;
    private javax.swing.JTextField TextEstado1;
    private javax.swing.JTextField TextEstadoViejo;
    private javax.swing.JTextField TextNombre1;
    private javax.swing.JTextField TextNombreViejo;
    private javax.swing.JTextField TextPrecio1;
    private javax.swing.JTextField TextPrecioViejo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
