/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poclibreria.gui;

import javax.swing.JOptionPane;
import poclibreria.Modelo.Libreria;
import poclibreria.Servicios.ServiciosLibreria;


/**
 *
 * @author USUARIO
 */
public class VentanaAgregarLibreria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAgregarLibreria.class.getName());

    /**
     * Creates new form VentanaAgregarLibreria
     */
    public VentanaAgregarLibreria() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textCodigoLibreria = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textPresupuesto = new javax.swing.JTextField();
        textCategoria = new javax.swing.JTextField();
        butSalir = new javax.swing.JButton();
        butAgregar = new javax.swing.JButton();
        checkDisponible = new javax.swing.JCheckBox();
        checkNoDisponible = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo libreria:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Presupuesto:");

        jLabel4.setText("Categoria:");

        jLabel5.setText("Estado:");

        jLabel6.setText("Agregar Libreria");

        textCodigoLibreria.addActionListener(this::textCodigoLibreriaActionPerformed);

        butSalir.setText("Salir");
        butSalir.addActionListener(this::butSalirActionPerformed);

        butAgregar.setText("Agregar");
        butAgregar.addActionListener(this::butAgregarActionPerformed);

        checkDisponible.setText("Diponible");

        checkNoDisponible.setText("No Disponible");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(butSalir))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                        .addComponent(textCategoria)
                                        .addComponent(textPresupuesto)
                                        .addComponent(textCodigoLibreria))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(butAgregar)
                                        .addGap(47, 47, 47))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(checkDisponible)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(checkNoDisponible))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textCodigoLibreria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(checkDisponible)
                        .addComponent(checkNoDisponible)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butSalir)
                    .addComponent(butAgregar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_butSalirActionPerformed

    private void butAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAgregarActionPerformed
        String nombre, strCodigoLibreria, strPresupuesto, estado, direccion;
        int codigoLibreria;
        double presupuesto;
        Libreria libreria;
        
    }//GEN-LAST:event_butAgregarActionPerformed

    private void textCodigoLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoLibreriaActionPerformed
 
    String strCodigo, strPresupuesto, nombre, categoria;
    int codigo;
    double presupuesto;
    Libreria libreria;
    boolean disponible;

    try {
        // 1. Lectura de campos de texto
        strCodigo = textCodigoLibreria.getText().strip();
        nombre = textNombre.getText().strip();
        strPresupuesto = textPresupuesto.getText().strip();
        categoria = textCategoria.getText().strip();

        // 2. Determinación del estado booleano mediante los CheckBox
        if (checkDisponible.isSelected() && !checkNoDisponible.isSelected()) {
            disponible = true;
        } else if (!checkDisponible.isSelected() && checkNoDisponible.isSelected()) {
            disponible = false;
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione únicamente una opción de disponibilidad (Sí o No).");
            return;
        }

        // 3. Conversión de texto a tipos numéricos primitivos
        codigo = Integer.parseInt(strCodigo);
        presupuesto = Double.parseDouble(strPresupuesto);

        // 4. Instanciación del objeto con los atributos del modelo
        libreria = new Libreria(codigo, nombre, presupuesto, categoria, disponible);

        // 5. Envío del objeto al servicio para su procesamiento
        ServiciosLibreria.ResultadoAgregar resultado = ServiciosLibreria.adicionarLibreria(libreria);

        switch (resultado) {
            case OK:
                JOptionPane.showMessageDialog(this, "La librería fue agregada exitosamente.");
                break;
            case CODIGO_REPETIDO:
                JOptionPane.showMessageDialog(this, "El código ingresado ya existe.");
                break;
            case NOMBRE_REPETIDO:
                JOptionPane.showMessageDialog(this, "El nombre de la librería ya existe.");
                break;
            default:
                JOptionPane.showMessageDialog(this, "Ocurrió un error al guardar los datos.");
                break;
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Asegúrese de ingresar números válidos en el código y el presupuesto.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

        
        
        
    }//GEN-LAST:event_textCodigoLibreriaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAgregar;
    private javax.swing.JButton butSalir;
    private javax.swing.JCheckBox checkDisponible;
    private javax.swing.JCheckBox checkNoDisponible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField textCategoria;
    private javax.swing.JTextField textCodigoLibreria;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPresupuesto;
    // End of variables declaration//GEN-END:variables
}
