/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poclibreria.gui;
import javax.swing.table.DefaultTableModel;
import poclibreria.Modelo.Libreria;
import java.util.List;
import poclibreria.Servicios.ServiciosLibreria;

/**
 *
 * @author USUARIO
 */
public class VentanaListadoLibreria extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaListadoLibreria.class.getName());

    /**
     * Creates new form VentanaListadoLibreria
     */
    public VentanaListadoLibreria() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrerias = new javax.swing.JTable();
        bntListar1 = new javax.swing.JButton();

        bntListar.setText("Listar");
        bntListar.addActionListener(this::bntListarActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblLibrerias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLibrerias);

        bntListar1.setText("Listar");
        bntListar1.addActionListener(this::bntListar1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bntListar1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bntListar1)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntListarActionPerformed
    
    }//GEN-LAST:event_bntListarActionPerformed

    private void bntListar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntListar1ActionPerformed
        List<Libreria> librerias = ServiciosLibreria.getLibrerias();;
        
        DefaultTableModel model = (DefaultTableModel) tblLibrerias.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(new Object[]{"Codigo", "Nombre", "Presupuesto", "Categoria", "Estado"});
        
        
       for (Libreria libreria : librerias) {
            model.addRow(new Object[]{
                libreria.getCodigoLibreria(),
                libreria.getNombre(),
                libreria.getPresupuesto(),
                libreria.getCategoria(),
                libreria.isDisponible() ? "Activa" : "Eliminada"
            });
        }
    }//GEN-LAST:event_bntListar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntListar;
    private javax.swing.JButton bntListar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLibrerias;
    // End of variables declaration//GEN-END:variables
}
