/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pocLibro.Gui;

import javax.swing.JOptionPane;
import pocLibro.Gui.VentanaBuscar;
import pocLibro.Gui.VentanaAgregar;
import pocLibro.Gui.VentanaContarRegistro;
import pocLibro.Gui.VentanaEliminarLibro;
import pocLibro.Gui.VentanaListado;
import pocLibro.Gui.VentanaSumatoria;
import pocLibro.Gui.VentanaActualizar;
import poclibreria.gui.VentanaAgregarLibreria;
import poclibreria.gui.VentanaBuscarLibreria;
import poclibreria.gui.VentanaListadoLibreria;
import poclibreria.gui.VentanaContarRegistroLibreria;
import poclibreria.gui.VentanaActualizarLibreria;
import poclibreria.gui.VentanaEliminar;



public class GuiPrincipal extends javax.swing.JFrame {
    

    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Libro = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Libreria = new javax.swing.JMenu();
        SubMenuAgregar = new javax.swing.JMenuItem();
        SubMenuBuscar = new javax.swing.JMenuItem();
        SubMenuEliminar = new javax.swing.JMenuItem();
        SubMenuListar = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        SubMenuAcerdaDe = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Libro.setText("Libro");

        jMenuItem2.setText("Actualizar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Libro.add(jMenuItem2);

        jMenuItem3.setText("Agregar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Libro.add(jMenuItem3);

        jMenuItem4.setText("Buscar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Libro.add(jMenuItem4);

        jMenuItem5.setText("Contar Registros");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        Libro.add(jMenuItem5);

        jMenuItem6.setText("Eliminar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        Libro.add(jMenuItem6);

        jMenuItem7.setText("Listar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        Libro.add(jMenuItem7);

        jMenuItem8.setText("Sumatoria");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        Libro.add(jMenuItem8);

        jMenuBar1.add(Libro);

        Libreria.setText("Libreria");

        SubMenuAgregar.setText("Agregar");
        SubMenuAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuAgregarActionPerformed(evt);
            }
        });
        Libreria.add(SubMenuAgregar);

        SubMenuBuscar.setText("Buscar");
        SubMenuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuBuscarActionPerformed(evt);
            }
        });
        Libreria.add(SubMenuBuscar);

        SubMenuEliminar.setText("Eliminar");
        SubMenuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuEliminarActionPerformed(evt);
            }
        });
        Libreria.add(SubMenuEliminar);

        SubMenuListar.setText("Listar");
        SubMenuListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuListarActionPerformed(evt);
            }
        });
        Libreria.add(SubMenuListar);

        jMenuItem9.setText("Contar Libreria");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        Libreria.add(jMenuItem9);

        jMenuBar1.add(Libreria);

        SubMenuAcerdaDe.setText("Ayuda");

        jMenuItem1.setText("Acerda de...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        SubMenuAcerdaDe.add(jMenuItem1);

        jMenuBar1.add(SubMenuAcerdaDe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Desarrolladó por: Nicolas Vargas, Manuel Delvasto, Alejandra Reina, Juan pablo acosta");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        VentanaActualizar ventanaActualizar = new VentanaActualizar();
        ventanaActualizar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        VentanaAgregar ventanaAgregar = new VentanaAgregar();
        ventanaAgregar.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       VentanaBuscar ventanaBuscar = new VentanaBuscar();
        ventanaBuscar.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        VentanaEliminarLibro ventanaEliminar = new VentanaEliminarLibro();
        ventanaEliminar.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        VentanaListado ventanaListar = new VentanaListado();
        ventanaListar.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        VentanaContarRegistro ventanaContar = new VentanaContarRegistro();
        ventanaContar.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        VentanaSumatoria ventanaSumatoria = new VentanaSumatoria();
        ventanaSumatoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void SubMenuAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuAgregarActionPerformed
    VentanaAgregarLibreria vAgregar = new VentanaAgregarLibreria();
    vAgregar.setVisible(true);
    }//GEN-LAST:event_SubMenuAgregarActionPerformed

    private void SubMenuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuBuscarActionPerformed
      VentanaActualizarLibreria vActualizar = new VentanaActualizarLibreria();
      vActualizar.setVisible(true);
    }//GEN-LAST:event_SubMenuBuscarActionPerformed

    private void SubMenuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuEliminarActionPerformed
    VentanaEliminar ventanaEliminar = new VentanaEliminar();
        ventanaEliminar.setVisible(true);
    }//GEN-LAST:event_SubMenuEliminarActionPerformed

    private void SubMenuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuListarActionPerformed
    VentanaListadoLibreria vListado = new VentanaListadoLibreria();
    vListado.setVisible(true);
    }//GEN-LAST:event_SubMenuListarActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
      VentanaContarRegistroLibreria vContar = new VentanaContarRegistroLibreria();
      vContar.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Libreria;
    private javax.swing.JMenu Libro;
    private javax.swing.JMenu SubMenuAcerdaDe;
    private javax.swing.JMenuItem SubMenuAgregar;
    private javax.swing.JMenuItem SubMenuBuscar;
    private javax.swing.JMenuItem SubMenuEliminar;
    private javax.swing.JMenuItem SubMenuListar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
