/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pocLibro.Gui;

import javax.swing.JOptionPane;
import pocLibro.Gui.VentanaBuscar;
import pocLibro.Gui.VentanaAgregar;
import pocLibro.Gui.VentanaContarRegistro;
import pocLibro.Gui.VentanaEliminar;
import pocLibro.Gui.VentanaListado;
import pocLibro.Gui.VentanaSumatoria;
import pocLibro.Gui.VentanaActualizar;
import pocLibreria.gui.GuiPrincipalLibreria;

public class GuiPrincipal extends javax.swing.JFrame {
    

    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuConsultas = new javax.swing.JMenu();
        SubMenuBuscarLibro = new javax.swing.JMenuItem();
        SubMenuListarLibro = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        SubMenuActualizarLibro = new javax.swing.JMenuItem();
        SubMenuSumatoriaLibros = new javax.swing.JMenuItem();
        SubMenuContarRegistros = new javax.swing.JMenuItem();
        SubMenuAcerdaDe = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuGUIParcia = new javax.swing.JMenu();
        subMenuGUIParcial = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuGestiones = new javax.swing.JMenu();
        SubMenuAgregarLibro = new javax.swing.JMenuItem();
        SubMenuEliminarLibro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuConsultas.setText("Consultas");

        SubMenuBuscarLibro.setText("Buscar Libro");
        SubMenuBuscarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuBuscarLibroActionPerformed(evt);
            }
        });
        MenuConsultas.add(SubMenuBuscarLibro);

        SubMenuListarLibro.setText("Listar Libro");
        SubMenuListarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuListarLibroActionPerformed(evt);
            }
        });
        MenuConsultas.add(SubMenuListarLibro);

        jMenuBar1.add(MenuConsultas);

        MenuReportes.setText("Reportes");

        SubMenuActualizarLibro.setText("Actualizar Libro");
        SubMenuActualizarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuActualizarLibroActionPerformed(evt);
            }
        });
        MenuReportes.add(SubMenuActualizarLibro);

        SubMenuSumatoriaLibros.setText("Sumatoria Precios");
        SubMenuSumatoriaLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuSumatoriaLibrosActionPerformed(evt);
            }
        });
        MenuReportes.add(SubMenuSumatoriaLibros);

        SubMenuContarRegistros.setText("Contar Registros");
        SubMenuContarRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuContarRegistrosActionPerformed(evt);
            }
        });
        MenuReportes.add(SubMenuContarRegistros);

        jMenuBar1.add(MenuReportes);

        SubMenuAcerdaDe.setText("Ayuda");

        jMenuItem1.setText("Acerda de...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        SubMenuAcerdaDe.add(jMenuItem1);

        jMenuBar1.add(SubMenuAcerdaDe);

        menuGUIParcia.setText("GUIParcial");

        subMenuGUIParcial.setText("GUIParcial");
        subMenuGUIParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMenuGUIParcialActionPerformed(evt);
            }
        });
        menuGUIParcia.add(subMenuGUIParcial);

        jMenuItem2.setText("GuiLibreria");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuGUIParcia.add(jMenuItem2);

        jMenuBar1.add(menuGUIParcia);

        MenuGestiones.setText("Gestiones");

        SubMenuAgregarLibro.setText("Agregar Libro");
        SubMenuAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuAgregarLibroActionPerformed(evt);
            }
        });
        MenuGestiones.add(SubMenuAgregarLibro);

        SubMenuEliminarLibro.setText("Eliminar Libro");
        SubMenuEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenuEliminarLibroActionPerformed(evt);
            }
        });
        MenuGestiones.add(SubMenuEliminarLibro);

        jMenuBar1.add(MenuGestiones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenuAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuAgregarLibroActionPerformed
        VentanaAgregar vAgregar = new VentanaAgregar();
        vAgregar.setVisible(true);
    }//GEN-LAST:event_SubMenuAgregarLibroActionPerformed

    private void SubMenuEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuEliminarLibroActionPerformed
        VentanaEliminar vEliminar = new VentanaEliminar();
        vEliminar.setVisible(true);
    }//GEN-LAST:event_SubMenuEliminarLibroActionPerformed

    private void SubMenuContarRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuContarRegistrosActionPerformed
        VentanaContarRegistro vContarRegistros = new VentanaContarRegistro();
        vContarRegistros.setVisible(true);
    }//GEN-LAST:event_SubMenuContarRegistrosActionPerformed

    private void SubMenuBuscarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuBuscarLibroActionPerformed
        VentanaBuscar vBuscar = new VentanaBuscar();
        vBuscar.setVisible(true);

    }//GEN-LAST:event_SubMenuBuscarLibroActionPerformed

    private void SubMenuSumatoriaLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuSumatoriaLibrosActionPerformed
    VentanaSumatoria  vSumatoria = new VentanaSumatoria();
    vSumatoria.setVisible(true);
    }//GEN-LAST:event_SubMenuSumatoriaLibrosActionPerformed

    private void SubMenuListarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuListarLibroActionPerformed
     VentanaListado vListado = new VentanaListado();
     vListado.setVisible(true);
    }//GEN-LAST:event_SubMenuListarLibroActionPerformed

    private void SubMenuActualizarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenuActualizarLibroActionPerformed
        VentanaActualizar vActualizar = new VentanaActualizar();
        vActualizar.setVisible(true);
    }//GEN-LAST:event_SubMenuActualizarLibroActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Desarrolladó por: Nicolas Vargas, Manuel Delvasto, Alejandra Reina");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void subMenuGUIParcialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMenuGUIParcialActionPerformed

    }//GEN-LAST:event_subMenuGUIParcialActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        GuiPrincipalLibreria
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuConsultas;
    private javax.swing.JMenu MenuGestiones;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JMenu SubMenuAcerdaDe;
    private javax.swing.JMenuItem SubMenuActualizarLibro;
    private javax.swing.JMenuItem SubMenuAgregarLibro;
    private javax.swing.JMenuItem SubMenuBuscarLibro;
    private javax.swing.JMenuItem SubMenuContarRegistros;
    private javax.swing.JMenuItem SubMenuEliminarLibro;
    private javax.swing.JMenuItem SubMenuListarLibro;
    private javax.swing.JMenuItem SubMenuSumatoriaLibros;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuGUIParcia;
    private javax.swing.JMenuItem subMenuGUIParcial;
    // End of variables declaration//GEN-END:variables
}
